version: '2'
services:
  jod:  
    image: processoeletronico/vagrant-sei4_jod:${ENVIRONMENT_VERSION}
    container_name: jod

  smtp:
    image: processoeletronico/vagrant-sei4_mailcatcher:${ENVIRONMENT_VERSION}
    container_name: smtp
    ports:
      - "1080:1080"

  memcached:
    image: processoeletronico/vagrant-sei4_memcached:${ENVIRONMENT_VERSION}
    container_name: memcached
    ports:
      - "11211:11211"

  database:
    image: ${DATABASE_IMAGE}
    container_name: ${DATABASE_HOST}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - ${DATABASE_HOST}:${DATABASE_DATA_DIR}
      #- /var/sei/${DATABASE_HOST}/backup:/backup

  solr:
    image: processoeletronico/vagrant-sei4_solr:${ENVIRONMENT_VERSION}
    container_name: solr
    ports:
      - "8983:8983"

  http:
    image: processoeletronico/vagrant-sei4_httpd:${ENVIRONMENT_VERSION}
    container_name: http
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on: 
      - database
    volumes:
      - ./FontesSEI:/opt
    environment:
      - XDEBUG_CONFIG="idekey=default remote_enable=1 remote_mode=req remote_port=9000 remote_host=10.0.2.2 remote_connect_back=1"
      - APP_SIP_CHAVE_ACESSO=${APP_SIP_CHAVE_ACESSO}
      - APP_SEI_CHAVE_ACESSO=${APP_SEI_CHAVE_ACESSO}
      - HOST_URL=http://localhost:8000
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}

      - SEI_DATABASE_NAME=${SEI_DATABASE_NAME}
      - SEI_DATABASE_USER=${SEI_DATABASE_USER}
      - SEI_DATABASE_PASSWORD=${SEI_DATABASE_PASSWORD}
      - SEI_DATABASE_USER_SCRIPT=${SEI_DATABASE_USER_SCRIPT}
      - SEI_DATABASE_PASSWORD_SCRIPT=${SEI_DATABASE_PASSWORD_SCRIPT}
      
      - SIP_DATABASE_NAME=${SIP_DATABASE_NAME}
      - SIP_DATABASE_USER=${SIP_DATABASE_USER}
      - SIP_DATABASE_PASSWORD=${SIP_DATABASE_PASSWORD}
      - SIP_DATABASE_USER_SCRIPT=${SIP_DATABASE_USER_SCRIPT}
      - SIP_DATABASE_PASSWORD_SCRIPT=${SIP_DATABASE_PASSWORD_SCRIPT}
    links:
      - database:${DATABASE_HOST}
      - memcached:memcached
      - solr:solr
      - smtp:smtp
      - jod:jod


volumes:
  mysql:
  oracle:
  sqlserver:
